### ISSUE TITLE
Continuously getting an sqlite error, help needed.

### ISSUE THREAD

**Issue by umangnangal** [RasaHQ/rasa-x-demo#29]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: model

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/sanic/app.py", line 976, in handle_request
    response = await response
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 166, in decorated_function
    return await await_and_return_response(args, kwargs, request)
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 142, in await_and_return_response
    response = await response
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/rasax/community/api/blueprints/models.py", line 103, in get_model_for_tag
    model = _model_service(request).model_for_tag(project_id, tag)
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/rasax/community/services/model_service.py", line 512, in model_for_tag
    .filter(and_(ModelTag.tag == tag, Model.project_id == project))
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3402, in first
    ret = list(self[0:1])
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3176, in __getitem__
    return list(res)
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/opt/anaconda3/envs/botenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: model
[SQL: SELECT model.id AS model_id, model.hash AS model_hash, model.name AS model_name, model.path AS model_path, model.project_id AS model_project_id, model.version AS model_version, model.trained_at AS model_trained_at 
FROM model JOIN model_tag ON model.id = model_tag.model_id 
WHERE model_tag.tag = ? AND model.project_id = ?
 LIMIT ? OFFSET ?]
[parameters: ('production', 'default', 1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
2020-09-09 17:26:53 ERROR    sanic.root  - Exception occurred while handling uri: 'http://localhost:5002/api/projects/default/models/tags/production?token=af9c632e4e90b49276e8904bf61cf2e0'

**Comment by sara-tagger** [comment]
Thanks for the issue, @tttthomasssss will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
